<?xml version="1.0" encoding="utf-8"?><!-- Copyright (C) 2010 The Android Open Source Project
     Copyright (C) 2013 - 2015 The Linux Foundation. All rights reserved.
     Not a contribution.

     Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.
--><!DOCTYPE MediaSettings [<!ELEMENT MediaSettings (CamcorderProfiles,EncoderOutputFileFormat+,VideoEncoderCap+,AudioEncoderCap+,VideoDecoderCap,AudioDecoderCap)><!ELEMENT CamcorderProfiles (EncoderProfile+, ImageEncoding+, ImageDecoding, Camera)><!ELEMENT EncoderProfile (Video, Audio)><!ATTLIST EncoderProfile quality (high|low) #REQUIRED><!ATTLIST EncoderProfile fileFormat (mp4|3gp) #REQUIRED><!ATTLIST EncoderProfile duration (30|60) #REQUIRED><!ATTLIST EncoderProfile cameraId (0|1) #REQUIRED><!ELEMENT Video EMPTY><!ATTLIST Video codec (h264|h263|m4v) #REQUIRED><!ATTLIST Video bitRate CDATA #REQUIRED><!ATTLIST Video width CDATA #REQUIRED><!ATTLIST Video height CDATA #REQUIRED><!ATTLIST Video frameRate CDATA #REQUIRED><!ELEMENT Audio EMPTY><!ATTLIST Audio codec (amrnb|amrwb|aac|lpcm) #REQUIRED><!ATTLIST Audio bitRate CDATA #REQUIRED><!ATTLIST Audio sampleRate CDATA #REQUIRED><!ATTLIST Audio channels (1|2|6) #REQUIRED><!ELEMENT ImageEncoding EMPTY><!ATTLIST ImageEncoding quality (90|80|70|60|50|40) #REQUIRED><!ELEMENT ImageDecoding EMPTY><!ATTLIST ImageDecoding memCap CDATA #REQUIRED><!ELEMENT Camera EMPTY><!ELEMENT EncoderOutputFileFormat EMPTY><!ATTLIST EncoderOutputFileFormat name (mp4|3gp) #REQUIRED><!ELEMENT VideoEncoderCap EMPTY><!ATTLIST VideoEncoderCap name (h265|h264|h263|m4v|wmv) #REQUIRED><!ATTLIST VideoEncoderCap enabled (true|false) #REQUIRED><!ATTLIST VideoEncoderCap minBitRate CDATA #REQUIRED><!ATTLIST VideoEncoderCap maxBitRate CDATA #REQUIRED><!ATTLIST VideoEncoderCap minFrameWidth CDATA #REQUIRED><!ATTLIST VideoEncoderCap maxFrameWidth CDATA #REQUIRED><!ATTLIST VideoEncoderCap minFrameHeight CDATA #REQUIRED><!ATTLIST VideoEncoderCap maxFrameHeight CDATA #REQUIRED><!ATTLIST VideoEncoderCap minFrameRate CDATA #REQUIRED><!ATTLIST VideoEncoderCap maxFrameRate CDATA #REQUIRED><!ELEMENT AudioEncoderCap EMPTY><!ATTLIST AudioEncoderCap name (amrnb|amrwb|aac|wma|lpcm) #REQUIRED><!ATTLIST AudioEncoderCap enabled (true|false) #REQUIRED><!ATTLIST AudioEncoderCap minBitRate CDATA #REQUIRED><!ATTLIST AudioEncoderCap maxBitRate CDATA #REQUIRED><!ATTLIST AudioEncoderCap minSampleRate CDATA #REQUIRED><!ATTLIST AudioEncoderCap maxSampleRate CDATA #REQUIRED><!ATTLIST AudioEncoderCap minChannels (1|2|6) #REQUIRED><!ATTLIST AudioEncoderCap maxChannels (1|2|6) #REQUIRED><!ELEMENT VideoDecoderCap EMPTY><!ATTLIST VideoDecoderCap name (wmv) #REQUIRED><!ATTLIST VideoDecoderCap enabled (true|false) #REQUIRED><!ELEMENT AudioDecoderCap EMPTY><!ATTLIST AudioDecoderCap name (wma) #REQUIRED><!ATTLIST AudioDecoderCap enabled (true|false) #REQUIRED>]><!--
     This file is used to declare the multimedia profiles and capabilities
     on an android-powered device.
-->
<MediaSettings>
    <!-- Each camcorder profile defines a set of predefined configuration parameters -->
    <!-- Back Camera -->
    <CamcorderProfiles cameraId="0" startOffsetMs="300">

        <EncoderProfile duration="30" fileFormat="3gp" quality="low">
            <Video bitRate="192000" codec="h264" frameRate="30" height="144" width="176" />

            <Audio bitRate="12200" channels="1" codec="amrnb" sampleRate="8000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="mp4" quality="high">
            <Video bitRate="42000000" codec="h264" frameRate="30" height="2160" width="3840" />

            <Audio bitRate="156000" channels="2" codec="aac" sampleRate="48000" />
        </EncoderProfile>

        <EncoderProfile duration="60" fileFormat="mp4" quality="qvga">
            <Video bitRate="512000" codec="h264" frameRate="30" height="240" width="320" />

            <Audio bitRate="156000" channels="2" codec="aac" sampleRate="48000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="3gp" quality="cif">
            <Video bitRate="720000" codec="h264" frameRate="30" height="288" width="352" />

            <Audio bitRate="12200" channels="1" codec="amrnb" sampleRate="8000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="mp4" quality="480p">
            <Video bitRate="2000000" codec="h264" frameRate="30" height="480" width="720" />
            <Audio bitRate="156000" channels="2" codec="aac" sampleRate="48000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="mp4" quality="720p">
            <Video bitRate="14000000" codec="h264" frameRate="30" height="720" width="1280" />
            <Audio bitRate="156000" channels="2" codec="aac" sampleRate="48000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="mp4" quality="1080p">
            <Video bitRate="20000000" codec="h264" frameRate="30" height="1080" width="1920" />

            <Audio bitRate="156000" channels="2" codec="aac" sampleRate="48000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="mp4" quality="4kdci">
            <Video bitRate="42000000" codec="h264" frameRate="24" height="2160" width="4096" />

            <Audio bitRate="156000" channels="2" codec="aac" sampleRate="48000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="mp4" quality="2160p">
            <Video bitRate="42000000" codec="h264" frameRate="30" height="2160" width="3840" />

            <Audio bitRate="156000" channels="2" codec="aac" sampleRate="48000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="3gp" quality="qcif">
            <Video bitRate="192000" codec="h264" frameRate="30" height="144" width="176" />

            <Audio bitRate="12200" channels="1" codec="amrnb" sampleRate="8000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="mp4" quality="vga">
            <Video bitRate="2000000" codec="h264" frameRate="30" height="480" width="640" />

            <Audio bitRate="156000" channels="2" codec="aac" sampleRate="48000" />
        </EncoderProfile>

        <!-- TIMELAPSE PROFILE for back-camera -->

        <EncoderProfile duration="30" fileFormat="mp4" quality="timelapselow">
            <Video bitRate="192000" codec="h264" frameRate="30" height="144" width="176" />

            <!-- audio setting is ignored -->
            <Audio bitRate="12200" channels="1" codec="amrnb" sampleRate="8000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="mp4" quality="timelapsehigh">
            <Video bitRate="42000000" codec="h264" frameRate="30" height="2160" width="3840" />

            <!-- audio setting is ignored -->
            <Audio bitRate="156000" channels="2" codec="aac" sampleRate="48000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="mp4" quality="timelapseqcif">
            <Video bitRate="192000" codec="h264" frameRate="30" height="144" width="176" />
            <!-- audio setting is ignored -->
            <Audio bitRate="12200" channels="1" codec="amrnb" sampleRate="8000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="mp4" quality="timelapsecif">
            <Video bitRate="720000" codec="h264" frameRate="30" height="288" width="352" />

            <!-- audio setting is ignored -->
            <Audio bitRate="12200" channels="1" codec="amrnb" sampleRate="8000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="mp4" quality="timelapseqvga">
            <Video bitRate="512000" codec="h264" frameRate="30" height="240" width="320" />

            <!-- audio setting is ignored -->
            <Audio bitRate="12200" channels="1" codec="amrnb" sampleRate="8000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="mp4" quality="timelapsevga">
            <Video bitRate="2000000" codec="h264" frameRate="30" height="480" width="640" />

            <!-- audio setting is ignored -->
            <Audio bitRate="12200" channels="1" codec="amrnb" sampleRate="8000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="mp4" quality="timelapse480p">
            <Video bitRate="2000000" codec="h264" frameRate="30" height="480" width="640" />
            <!-- audio setting is ignored -->
            <Audio bitRate="156000" channels="2" codec="aac" sampleRate="48000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="mp4" quality="timelapse720p">
            <Video bitRate="14000000" codec="h264" frameRate="30" height="720" width="1280" />
            <!-- audio setting is ignored -->
            <Audio bitRate="156000" channels="2" codec="aac" sampleRate="48000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="mp4" quality="timelapse1080p">
            <Video bitRate="20000000" codec="h264" frameRate="30" height="1080" width="1920" />
            <!-- audio setting is ignored -->
            <Audio bitRate="156000" channels="2" codec="aac" sampleRate="48000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="mp4" quality="timelapse4kdci">
            <Video bitRate="42000000" codec="h264" frameRate="30" height="2160" width="4096" />

            <Audio bitRate="156000" channels="2" codec="aac" sampleRate="48000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="mp4" quality="timelapse2160p">
            <Video bitRate="42000000" codec="h264" frameRate="30" height="2160" width="3840" />

            <Audio bitRate="156000" channels="2" codec="aac" sampleRate="48000" />
        </EncoderProfile>

        <!-- CAMCORDER_QUALITY_HIGH_SPEED_LOW/720P : 720p@120fps; 27.0 Mbps -->
        <EncoderProfile duration="30" fileFormat="mp4" quality="highspeedlow">
            <Video bitRate="27000000" codec="h264" frameRate="120" height="720" width="1280" />
            <!-- audio setting is ignored -->
            <Audio bitRate="96000" channels="2" codec="aac" sampleRate="48000" />
        </EncoderProfile>

        <!-- CAMCORDER_QUALITY_HIGH_SPEED_HIGH/720P : 720p@120fps; 27.0 Mbps -->
        <EncoderProfile duration="30" fileFormat="mp4" quality="highspeedhigh">
            <Video bitRate="27000000" codec="h264" frameRate="120" height="720" width="1280" />
            <!-- audio setting is ignored -->
            <Audio bitRate="96000" channels="2" codec="aac" sampleRate="48000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="mp4" quality="highspeed720p">
            <Video bitRate="27000000" codec="h264" frameRate="120" height="720" width="1280" />
            <!-- audio setting is ignored -->
            <Audio bitRate="96000" channels="2" codec="aac" sampleRate="48000" />
        </EncoderProfile>

        <!-- CAMCORDER_QUALITY_HIGH_SPEED_HIGH/1080P : 1080p@60fps; 34.0 Mbps -->
        <EncoderProfile duration="30" fileFormat="mp4" quality="highspeed1080p">
            <Video bitRate="34000000" codec="h264" frameRate="60" height="1080" width="1920" />
            <!-- audio setting is ignored -->
            <Audio bitRate="96000" channels="2" codec="aac" sampleRate="48000" />
        </EncoderProfile>

        <ImageEncoding quality="95" />
        <ImageEncoding quality="80" />
        <ImageEncoding quality="70" />
        <ImageDecoding memCap="20000000" />

    </CamcorderProfiles>

    <!-- Front Camera -->
    <CamcorderProfiles cameraId="1" startOffsetMs="300">

        <EncoderProfile duration="30" fileFormat="3gp" quality="low">
            <Video bitRate="192000" codec="h264" frameRate="30" height="144" width="176" />

            <Audio bitRate="12200" channels="1" codec="amrnb" sampleRate="8000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="mp4" quality="high">
            <Video bitRate="20000000" codec="h264" frameRate="30" height="1080" width="1920" />

            <Audio bitRate="156000" channels="2" codec="aac" sampleRate="48000" />
        </EncoderProfile>

        <EncoderProfile duration="60" fileFormat="mp4" quality="qvga">
            <Video bitRate="512000" codec="h264" frameRate="30" height="240" width="320" />

            <Audio bitRate="156000" channels="2" codec="aac" sampleRate="48000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="3gp" quality="cif">
            <Video bitRate="720000" codec="h264" frameRate="30" height="288" width="352" />

            <Audio bitRate="12200" channels="1" codec="amrnb" sampleRate="8000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="mp4" quality="480p">
            <Video bitRate="2000000" codec="h264" frameRate="30" height="480" width="720" />
            <Audio bitRate="156000" channels="2" codec="aac" sampleRate="48000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="mp4" quality="720p">
            <Video bitRate="14000000" codec="h264" frameRate="30" height="720" width="1280" />
            <Audio bitRate="156000" channels="2" codec="aac" sampleRate="48000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="mp4" quality="1080p">
            <Video bitRate="20000000" codec="h264" frameRate="30" height="1080" width="1920" />

            <Audio bitRate="156000" channels="2" codec="aac" sampleRate="48000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="3gp" quality="qcif">
            <Video bitRate="192000" codec="h264" frameRate="30" height="144" width="176" />

            <Audio bitRate="12200" channels="1" codec="amrnb" sampleRate="8000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="mp4" quality="vga">
            <Video bitRate="2000000" codec="h264" frameRate="30" height="480" width="640" />

            <Audio bitRate="156000" channels="2" codec="aac" sampleRate="48000" />
        </EncoderProfile>

        <!-- TIMELAPSE profiles for front camera -->
        <EncoderProfile duration="30" fileFormat="mp4" quality="timelapselow">
            <Video bitRate="192000" codec="h264" frameRate="30" height="144" width="176" />

            <!-- audio setting is ignored -->
            <Audio bitRate="12200" channels="1" codec="amrnb" sampleRate="8000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="mp4" quality="timelapsehigh">
            <Video bitRate="20000000" codec="h264" frameRate="30" height="1080" width="1920" />

            <!-- audio setting is ignored -->
            <Audio bitRate="156000" channels="2" codec="aac" sampleRate="48000" />
        </EncoderProfile>
        <EncoderProfile duration="30" fileFormat="mp4" quality="timelapseqcif">
            <Video bitRate="192000" codec="h264" frameRate="30" height="144" width="176" />
            <!-- audio setting is ignored -->
            <Audio bitRate="12200" channels="1" codec="amrnb" sampleRate="8000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="mp4" quality="timelapsecif">
            <Video bitRate="1200000" codec="h264" frameRate="30" height="288" width="352" />
            <!-- audio setting is ignored -->
            <Audio bitRate="96000" channels="1" codec="aac" sampleRate="48000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="mp4" quality="timelapseqvga">
            <Video bitRate="512000" codec="h264" frameRate="30" height="240" width="320" />

            <!-- audio setting is ignored -->
            <Audio bitRate="12200" channels="1" codec="amrnb" sampleRate="8000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="mp4" quality="timelapsevga">
            <Video bitRate="2000000" codec="h264" frameRate="30" height="480" width="640" />

            <!-- audio setting is ignored -->
            <Audio bitRate="12200" channels="1" codec="amrnb" sampleRate="8000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="mp4" quality="timelapse480p">
            <Video bitRate="5000000" codec="h264" frameRate="30" height="480" width="720" />
            <!-- audio setting is ignored -->
            <Audio bitRate="96000" channels="1" codec="aac" sampleRate="48000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="mp4" quality="timelapse720p">
            <Video bitRate="8000000" codec="h264" frameRate="30" height="720" width="1280" />
            <!-- audio setting is ignored -->
            <Audio bitRate="96000" channels="1" codec="aac" sampleRate="48000" />
        </EncoderProfile>

        <EncoderProfile duration="30" fileFormat="mp4" quality="timelapse1080p">
            <Video bitRate="20000000" codec="h264" frameRate="30" height="1080" width="1920" />

            <!-- audio setting is ignored -->
            <Audio bitRate="156000" channels="2" codec="aac" sampleRate="48000" />
        </EncoderProfile>

        <ImageEncoding quality="95" />
        <ImageEncoding quality="80" />
        <ImageEncoding quality="70" />
        <ImageDecoding memCap="20000000" />

    </CamcorderProfiles>

    <EncoderOutputFileFormat name="3gp" />
    <EncoderOutputFileFormat name="mp4" />

    <!--
         If a codec is not enabled, it is invisible to the applications
         In other words, the applications won't be able to use the codec
         or query the capabilities of the codec at all if it is disabled
    -->
    <VideoEncoderCap name="h264" enabled="true" maxBitRate="42000000" maxFrameHeight="2160"
        maxFrameRate="30" maxFrameWidth="4096" minBitRate="64000" minFrameHeight="144"
        minFrameRate="15" minFrameWidth="176" />

    <VideoEncoderCap name="h263" enabled="true" maxBitRate="2000000" maxFrameHeight="480"
        maxFrameRate="30" maxFrameWidth="800" minBitRate="64000" minFrameHeight="144"
        minFrameRate="15" minFrameWidth="176" />

    <VideoEncoderCap name="m4v" enabled="true" maxBitRate="20000000" maxFrameHeight="1088"
        maxFrameRate="30" maxFrameWidth="1920" minBitRate="64000" minFrameHeight="144"
        minFrameRate="15" minFrameWidth="176" />

    <VideoEncoderCap name="h265" enabled="true" maxBitRate="100000000" maxFrameHeight="2160"
        maxFrameRate="30" maxFrameWidth="4096" maxHFRFrameHeight="0" maxHFRFrameWidth="0"
        maxHFRMode="0" minBitRate="64000" minFrameHeight="144" minFrameRate="15"
        minFrameWidth="176" />

    <AudioEncoderCap name="aac" enabled="true" maxBitRate="96000" maxChannels="6"
        maxSampleRate="48000" minBitRate="8000" minChannels="1" minSampleRate="8000" />

    <AudioEncoderCap name="heaac" enabled="true" maxBitRate="64000" maxChannels="1"
        maxSampleRate="48000" minBitRate="8000" minChannels="1" minSampleRate="16000" />

    <AudioEncoderCap name="aaceld" enabled="true" maxBitRate="192000" maxChannels="1"
        maxSampleRate="48000" minBitRate="16000" minChannels="1" minSampleRate="16000" />

    <AudioEncoderCap name="amrwb" enabled="true" maxBitRate="23850" maxChannels="1"
        maxSampleRate="16000" minBitRate="6600" minChannels="1" minSampleRate="16000" />

    <AudioEncoderCap name="amrnb" enabled="true" maxBitRate="12200" maxChannels="1"
        maxSampleRate="8000" minBitRate="5525" minChannels="1" minSampleRate="8000" />

    <AudioEncoderCap name="lpcm" enabled="true" maxBitRate="4608000" maxChannels="6"
        maxSampleRate="48000" minBitRate="768000" minChannels="1" minSampleRate="8000" />

    <!--
        FIXME:
        We do not check decoder capabilities at present
        At present, we only check whether windows media is visible
        for TEST applications. For other applications, we do
        not perform any checks at all.
    -->
    <VideoDecoderCap name="wmv" enabled="true" />
    <AudioDecoderCap name="wma" enabled="true" />

</MediaSettings>
